# Generated by Django 6.0.4 on 2026-04-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lanceur', models.CharField(choices=[('ETUDIANT', 'Etudiant'), ('CHEF_DEPT', 'Chef Dept'), ('DIR_ADJOINT', 'Dir Adjoint')], max_length=20)),
                ('est_officielle', models.BooleanField(default=False)),
                ('taux_global', models.FloatField()),
                ('niveau_alerte', models.CharField(choices=[('VERT', 'Original (0–15%)'), ('ORANGE', 'Similarité modérée (16–30%)'), ('ROUGE', 'Forte similarité (31–50%)'), ('CRITIQUE', 'Plagiat probable (>50%)')], max_length=10)),
                ('passages', models.JSONField(default=list)),
                ('sources', models.JSONField(default=list)),
                ('rapport_pdf_path', models.CharField(blank=True, max_length=500)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('duree_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Analyse anti-plagiat',
                'db_table': 'analyses',
            },
        ),
    ]
