# Generated by Django 6.0.4 on 2026-04-27 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyses', '0001_initial'),
        ('rapports', '0001_initial'),
        ('themes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='lanceur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_lancees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyse',
            name='rapport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='rapports.rapportstage'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='themes.themestage'),
        ),
    ]
