# Generated by Django 6.0.4 on 2026-04-27 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions_academiques', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('fichier_path', models.CharField(max_length=500)),
                ('fichier_anonymise_path', models.CharField(max_length=500)),
                ('statut', models.CharField(choices=[('SOUMIS', 'Soumis'), ('ANALYSE_CHEF', 'Analysé par le chef'), ('DECISION_CHEF', 'Décision chef rendue'), ('VALIDE_DEF', 'Validé définitivement'), ('REFUSE_DEF', 'Refusé définitivement'), ('EN_REVISION', 'En révision'), ('ERREUR_EXTRACTION', 'Erreur extraction')], default='SOUMIS', max_length=25)),
                ('taux_similarite_global', models.FloatField(blank=True, null=True)),
                ('decision_chef', models.CharField(blank=True, choices=[('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('CORRECTIONS', 'Corrections demandées')], max_length=20)),
                ('commentaire_chef', models.TextField(blank=True)),
                ('decision_finale', models.CharField(blank=True, choices=[('VALIDE_DEF', 'Validé définitivement'), ('REFUSE_DEF', 'Refusé définitivement'), ('EN_REVISION', 'En révision')], max_length=20)),
                ('commentaire_final', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_decision_chef', models.DateTimeField(blank=True, null=True)),
                ('date_decision_finale', models.DateTimeField(blank=True, null=True)),
                ('decideur_chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_decides_chef', to=settings.AUTH_USER_MODEL)),
                ('decideur_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_decides_final', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions_academiques.sessionacademique')),
            ],
            options={
                'verbose_name': 'Rapport de stage',
                'db_table': 'rapports_stage',
            },
        ),
    ]
