# Generated by Django 6.0.4 on 2026-04-27 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions_academiques', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=300)),
                ('fichier_path', models.CharField(blank=True, max_length=500)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ANALYSE', 'Analysé'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('A_REFORMULER', 'À reformuler')], default='EN_ATTENTE', max_length=20)),
                ('commentaire_chef', models.TextField(blank=True)),
                ('taux_similarite', models.FloatField(blank=True, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('decideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes_decides', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='sessions_academiques.sessionacademique')),
                ('theme_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='themes.themestage')),
            ],
            options={
                'verbose_name': 'Thème de stage',
                'db_table': 'themes_stage',
            },
        ),
    ]
