# Generated by Django 6.0.4 on 2026-04-27 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SESSION_THEME', 'Session Thème'), ('SESSION_RAPPORT', 'Session Rapport')], max_length=20)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('FERMEE', 'Fermée')], default='OUVERTE', max_length=10)),
                ('date_ouverture', models.DateTimeField()),
                ('date_fermeture', models.DateTimeField()),
                ('promotion', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session académique',
                'db_table': 'sessions_academiques',
            },
        ),
    ]
