# Generated by Django 6.0.4 on 2026-04-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=10)),
                ('taux_detecte', models.FloatField()),
                ('notifie_chef', models.BooleanField(default=False)),
                ('notifie_dir', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alertes',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entite_type', models.CharField(max_length=50)),
                ('entite_id', models.PositiveIntegerField(null=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationSeuils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration seuils',
                'db_table': 'configuration_seuils',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_sha256', models.CharField(max_length=64)),
                ('signature_rsa', models.TextField()),
                ('date_signature', models.DateTimeField(auto_now_add=True)),
                ('fichier_signe_path', models.CharField(max_length=500)),
                ('valide', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'signatures',
            },
        ),
    ]
